spring:
  application:
    name: payments-hexagonal
  datasource:
    url: jdbc:mysql://localhost:3306/paymentshexagonal?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1000
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: full

clients:
  fraud-api:
    url: http://localhost:8081
  notifications-api:
    url: http://localhost:8081

topics:
  bootstrap-address: localhost:9092
  payment-info:
    name: payments.info
    partitions: 3
    replication-factor: 1
    group-id: payments-group01

# Kafka Logs
logging:
  level:
    com.mv.hexagonal.payments.adapters.out.client: DEBUG
    org:
      springframework.kafka.*: OFF
    springframework:
      kafka:
        listener:
          [KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF
