spring:
  application:
    name: payments-hexagonal
  datasource:
    url: jdbc:mysql://localhost:3308/payments-hexagonal?createDatabaseIfNotExist=true
    db: payments-hexagonal
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1000
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
